# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'Covid19App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Covid19App

pod 'Google-Mobile-Ads-SDK'

  target 'Covid19AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
